server:
  port: 8080

spring:
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  datasource:
    url: jdbc:mysql://db.chenquan.im:3306/dev
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true